### ISSUE TITLE
Problem sorting n elements where n is so big

### ISSUE THREAD

**Issue by JosepRivaille** [JosepRivaille/B7_PLSpeed#1]
Elements are passed as parameters and there's a bug where argv is big enough (f.e >= 1.000.000)
In each execution, random vector elements should be stored in a file and read that data in each C++ and Go source codes.

**Comment by paurisa** [comment]
Could the parameters be read from an external file? Maybe this way we can avoid this little bug (although it's not a very clean way to fix this).

**Comment by JosepRivaille** [comment]
Solved with last commit! :D
